version: '3.8'
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    container_name: rains_app
    restart: always
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    healthcheck:
      interval: 120ms
      retries: 5
      start_period: 60ms
      test: |
        touch /tmp/healthcheck.txt &&
        mkdir /tmp/healthcheck &&
        mv /tmp/healthcheck.txt /tmp/healthcheck &&
        cd /tmp/healthcheck &&
        echo "hello my docker container is working fine" >> healthcheck.txt &&
        cat healthcheck.txt &&
        rm healthcheck.txt &&
        cd .. &&
        rmdir /tmp/healthcheck
        cls
      timeout: 60ms
    env_file:
      - .env
    ports:
      - 4000:4000
    networks:
      - restapi_network
    depends_on:
      - db
  ### ===================
  ### DB SERVICE
  ### ===================
  db:
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    image: mysql:5.7
    restart: always
    container_name: rains_db
    environment:
        MYSQL_DATABASE: 'rains'
        MYSQL_ROOT_PASSWORD: 'rainsadmin123'
        MYSQL_USER: 'rains_admin'
        MYSQL_PASSWORD: 'rainsadmin123'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - restapi_network
  ### ===================
  ### ADMINER SERVICE
  ### ===================
  panel:
    image: adminer:latest
    restart: always
    healthcheck:
      interval: 120ms
      retries: 5
      start_period: 60ms
      test: |
        touch /tmp/healthcheck.txt &&
        mkdir /tmp/healthcheck &&
        mv /tmp/healthcheck.txt /tmp/healthcheck &&
        cd /tmp/healthcheck &&
        echo "hello my docker container is working fine" >> healthcheck.txt &&
        cat healthcheck.txt &&
        rm healthcheck.txt &&
        cd .. &&
        rmdir /tmp/healthcheck
        cls
      timeout: 60ms
    ports:
      - 8080:8080
    networks:
      - restapi_network
  ### ===================
  ### SWAGGER SERVICE
  ### ===================
#  doc:
#    build:
#      context: .
#      dockerfile: docker/swagger/Dockerfile
#    restart: always
#    healthcheck:
#      interval: 120ms
#      retries: 5
#      start_period: 60ms
#      test: |
#        touch /tmp/healthcheck.txt &&
#        mkdir /tmp/healthcheck &&
#        mv /tmp/healthcheck.txt /tmp/healthcheck &&
#        cd /tmp/healthcheck &&
#        echo "hello my docker container is working fine" >> healthcheck.txt &&
#        cat healthcheck.txt &&
#        rm healthcheck.txt &&
#        cd .. &&
#        rmdir /tmp/healthcheck
#        cls
#      timeout: 60ms
#    environment:
#      - URL=http://localhost/openapi.yml
#      - SWAGGER_JSON=swagger/openapi.yml
#    ports:
#      - 80:8080
#    networks:
#      - restapi_network
  ### ========================
  ### VOLUMES PERSISTENT DATA
  ### ========================
volumes:
  my-db:
  ### ===================================
  ### NETWORKS GROUP FOR ONE SAME SERVICE
  ### ===================================
networks:
  restapi_network: